### ISSUE TITLE
AttributeError: 'Settings' object has no attribute 'SLACK_CLIENT'

### ISSUE THREAD

**Issue by Prifido** [monzo/response#119]
I installed the response app using pip. After attempting to use the slash command to create an incident, I received the following error. Could anyone provide some guidance on how to address it?:

AttributeError: 'Settings' object has no attribute 'SLACK_CLIENT'

**Comment by Prifido** [comment]
Here is the full error message. Some guidance on this would be greatly appreciated:

Traceback (most recent call last):
  File "/Users/username/slack_response/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/username/slack_response/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/username/slack_response/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/username/slack_response/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/username/slack_response/lib/python3.7/site-packages/response/slack/authentication.py", line 34, in wrapper
    return f(*args, **kwargs)
  File "/Users/username/slack_response/lib/python3.7/site-packages/response/slack/views.py", line 51, in slash_command
    dialog.send_open_dialog(INCIDENT_REPORT_DIALOG, trigger_id)
  File "/Users/username/slack_response/lib/python3.7/site-packages/response/slack/dialog_builder.py", line 40, in send_open_dialog
    return settings.SLACK_CLIENT.dialog_open(
  File "/Users/username/slack_response/lib/python3.7/site-packages/django/conf/__init__.py", line 80, in __getattr__
    val = getattr(self._wrapped, name)

**Comment by danpalmer** [comment]
I've just experienced the same, it turned out to be some missing documentation. I've updated the README in this PR: https://github.com/monzo/response/pull/126 – you should be able to apply this to resolve the problem.

**Comment by milesbxf** [comment]
I've just merged #126, so closing this. Thanks for reporting and thanks for the PR!
