### ISSUE TITLE
Error on incident creation

### ISSUE THREAD

**Issue by LyfegenJames** [monzo/response#6]
Any thoughts on the below?

```
response    | [04/May/2019 07:55:08] "POST /slack/slash_command HTTP/1.1" 500 161449
response    | Internal Server Error: /slack/slash_command
response    | Traceback (most recent call last):
response    |   File "/app/slack/signals.py", line 21, in update_headline_after_incident_save
response    |     incident=instance
response    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_meth
od
response    |     return getattr(self.get_queryset(), name)(*args, **kwargs)
response    |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 399, in get
response    |     self.model._meta.object_name
response    | slack.models.headline_post.HeadlinePost.DoesNotExist: HeadlinePost matching query does not exist.
response    | 
response    | During handling of the above exception, another exception occurred:
response    | 
response    | Traceback (most recent call last):
response    |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
response    |     response = get_response(request)
response    |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_respo
nse
response    |     response = self.process_exception_by_middleware(e, request)
response    |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_respo
nse
response    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
response    |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_
view
response    |     return view_func(*args, **kwargs)
response    |   File "/app/slack/authentication.py", line 34, in wrapper
response    |     return f(*args, **kwargs)
response    |   File "/app/slack/views.py", line 40, in slash_command

```

**Comment by nagelflorian** [comment]
@LyfegenJames I just ran into these error logs too. After a bit of investigation I found out that the application wasn’t able to find the incidents channel `'error': 'channel_not_found’`. After checking permissions twice 😅 I finally found out that [`#incidents`](https://github.com/monzo/response/blob/master/env.example#L3) isn't the correct value for the env variable `INCIDENT_CHANNEL_NAME`. Instead removing the # symbol from it, i.e. just `incidents` worked for me. Perhaps you can try this too. If you can verify that this is the case for you too, perhaps we should discuss updating the `env.example` file then.

**Comment by LyfegenJames** [comment]
Thanks @nagelflorian I can confirm this was a good fix for me also.

**Comment by nagelflorian** [comment]
@evnsio I am curious to hear what your thoughts are on updating the [`env.example`](https://github.com/monzo/response/blob/master/env.example#L3) file to no longer include the `#` to perhaps prevent this particular issue from occurring again.

**Comment by evnsio** [comment]
Agree with fixing the the example env file.  Have merged the PR.  Thanks for flagging and fixing.
