### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by dwarkab** [monzo/response#98]
[Untitled 1.docx](https://github.com/monzo/response/files/3499825/Untitled.1.docx)

**ATTACH WHOLE ERROR AND MY SCRIPT DOCUMENT WITH THIS**

Hello,
I am trying to display form fields in report but following error occur.
Error:​
odoo.addons.base.ir.ir_qweb.qweb.QWebException: 'NoneType' object is not subscriptable
Traceback (most recent call last):
File "/usr/local/sampada/eclipse-workspace/odoo11/odoo/addons/base/ir/ir_qweb/qweb.py", line 343, in _compiled_fn
return compiled(self, append, new, options, log)
File "<template>", line 1, in template_1018_120
File "<template>", line 2, in body_call_content_119
File "<template>", line 3, in body_call_content_118
TypeError: 'NoneType' object is not subscriptable

**Comment by milesbxf** [comment]
Hi @dwarkab, I think you have the wrong repository here - this looks related to odoo and not response
